// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Lucene.Net.Contrib.Management")]
[assembly: AssemblyDescriptionAttribute("Lucene.Net.Contrib.Management")]
[assembly: AssemblyProductAttribute("Lucene.Net.Contrib.Management")]
[assembly: AssemblyVersionAttribute("1.0.3")]
[assembly: AssemblyInformationalVersionAttribute("1.0.3")]
[assembly: AssemblyFileVersionAttribute("1.0.3")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.3";
    }
}
